export const FileStorageABI = [
  { type: "constructor", payable: false, inputs: [] },
  {
    type: "event",
    anonymous: false,
    name: "FileDeleted",
    inputs: [Array],
  },
  {
    type: "event",
    anonymous: false,
    name: "FileUploaded",
    inputs: [Array],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnerPulseRefreshed",
    inputs: [Array],
  },
  {
    type: "event",
    anonymous: false,
    name: "ReleaseOwnerFiles",
    inputs: [Array],
  },
  {
    type: "function",
    name: "deleteFile",
    constant: false,
    payable: false,
    inputs: [Array],
    outputs: [],
  },
  {
    type: "function",
    name: "fileCount",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [Array],
  },
  {
    type: "function",
    name: "files",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [Array],
    outputs: [Array],
  },
  {
    type: "function",
    name: "getFile",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [Array],
    outputs: [Array],
  },
  {
    type: "function",
    name: "name",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [Array],
  },
  {
    type: "function",
    name: "releaseFilesToPublic",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateListingfunction",
    constant: false,
    payable: false,
    inputs: [Array],
    outputs: [],
  },
  {
    type: "function",
    name: "updateOwnerPulse",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "uploadFile",
    constant: false,
    payable: false,
    inputs: [Array],
    outputs: [],
  },
];
